### ISSUE TITLE
Provide Usage Examples for ZStack Layer

### ISSUE THREAD

**Issue by roboprint** [shimmeringbee/zstack#8]
Hello, could you please provide examples of using your library in real life?

A simple Hello World application, for example.

Thank you!

**Comment by pwood** [comment]
Hello @roboprint, apologies for the slow reply, for some reason GitHub didn't send me a notification.

At current it's not usable for any real purpose, while it can instantiate a network, allow joining, etc, it's realistically missing features such as end point enumeration, binding, sending and receiving ZCL messages.

I'll be working on these features over the next week or so. Once the zstack library is useful, I'll be moving onto a zcl library and a "hub" style application, which a much higher level of abstraction.

I will update the zstack readme though with examples, once it's functionally complete.

**Comment by roboprint** [comment]
@pwood thank you!
